<?php 
include_once "../../wp-config.php";
global $wpdb;

if($_SERVER["REQUEST_METHOD"] == "POST")
{
    
    if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
    }
    
    $uploadedfile = $_FILES['image'];
    
    $upload_overrides = array( 'test_form' => false );
    
    $ModulePicture = wp_handle_upload( $uploadedfile, $upload_overrides );
    
    if ( $ModulePicture && ! isset( $ModulePicture['error'] ) ) {
        //echo "File is valid, and was successfully uploaded.\n";
        //var_dump( $ModulePicture );
    } else {
        /**
         * Error generated by _wp_handle_upload()
         * @see _wp_handle_upload() in wp-admin/includes/file.php
         */
        //echo $ModulePicture['error'];
        
    }
    echo $ModulePicture['url'];
}

?>